from dataclasses import Field
from typing import Any, Dict, List, Literal, Optional, Protocol, Tuple, TypeVar, Generic, Type, Union, overload

TEntity = TypeVar('TEntity')

class Repository(Generic[TEntity], Protocol):
    """Базовый репозиторий с общей логикой"""

    @overload
    async def get_by_id(self, id: int, auto_error: Literal[True]) -> TEntity: ...

    @overload
    async def get_by_id(self, id: int, auto_error: Literal[False]) -> Optional[TEntity]: ...
    
    async def get_by_id(self, id: int, auto_error: bool = False) -> Optional[TEntity]: ...


    @overload
    async def get_or_create(self, auto_error: Literal[True], defaults: Optional[Dict[str, Any]] = None, **kwargs) -> TEntity: ...

    @overload
    async def get_or_create(self, auto_error: Literal[False], defaults: Optional[Dict[str, Any]] = None, **kwargs) -> Tuple[TEntity, bool]: ...

    @overload
    async def get_or_create(self, auto_error: None = None, defaults: Optional[Dict[str, Any]] = None, **kwargs) -> Tuple[TEntity, bool]: ...

    async def get_or_create(self, auto_error: Optional[bool] = False, defaults: Optional[Dict[str, Any]] = None, **kwargs) -> Any: ...
    

    @overload
    async def get_or_none(self, auto_error: Literal[False], **kwargs) -> Optional[TEntity]: ...

    @overload
    async def get_or_none(self, auto_error: Literal[True], **kwargs) -> TEntity: ...
    
    async def get_or_none(self, auto_error: bool = False, **kwargs) -> Optional[TEntity]: ...


    # async def update_all(self, update_data: Dict[str, Any], **where) -> int: ...
    

    async def select(self, **filters) -> List[TEntity]: ...

    async def count(self, **kwargs) -> int: ...
    

    async def delete(self, entity: TEntity) -> bool: ... 


    async def save(self, entity: TEntity) -> TEntity: ...

    async def load_relations(self, entity: TEntity, mapper: Dict[Union[str, Field, Tuple[Union[str, Field]]], "Repository"]) -> TEntity: ...