FROM python:3.12.6
WORKDIR /app
COPY ./backend ./backend
RUN pip install -e ./backend
EXPOSE 8000
WORKDIR /app/backend
# RUN python ./infrastructure/common/models/peewee_models.py
CMD [ "granian", "main:app", "--host", "0.0.0.0", "--port", "8000", "--interface", "asgi", "--workers", "20" ]
