FROM python:3.12.9
WORKDIR /app

COPY ./backend/setup.py ./

RUN pip install -e .

COPY ./backend ./

EXPOSE 8000

CMD [ "granian", "main:app", "--host", "0.0.0.0", "--port", "8000", "--interface", "asgi", "--workers", "8", "--loop", "uvloop", "--threads", "4" ]